### O'zgaruvchi e'lon qilish (qulaylik uchun)
@baseUrl = http://localhost:3000

### 1. Yangi foydalanuvchi yaratish (POST)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}

### 2. Barcha foydalanuvchilarni olish (GET)
GET {{baseUrl}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJpYXQiOjE3Njk1OTU1OTEsImV4cCI6MTc2OTU5OTE5MX0.mKnZSSZNX-9sX-dzsU8Z56iALxgbYhNaQ3BR2Nt37S0

# {
#   "total": 3,
#   "page": 1,
#   "limit": 10,
#   "items": [...]
# }

### 3. Bitta foydalanuvchini ID orqali olish (GET)
# Bu yerda 1 - foydalanuvchi IDsi. Agar u yo'q bo'lsa 404 qaytadi.
GET {{baseUrl}}/users/1

### 4. Foydalanuvchi ma'lumotini yangilash (PUT)
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
    "name": "Vali"
}

### 5. Foydalanuvchini o'chirish (DELETE)
# Sizda @HttpCode(204) qo'yilgan, shuning uchun muvaffaqiyatli bo'lsa javob bo'sh qaytadi.
DELETE {{baseUrl}}/users/1