@baseUrl = http://localhost:3000/api/v1

### 1) First call (DB)
GET {{baseUrl}}/users?page=1&limit=5

### 2) Second call (Redis cached: true bo‘lishi kerak)
GET {{baseUrl}}/users?page=1&limit=5

### 3) Create user -> cache clears
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "cachetest{{$timestamp}}@test.com",
  "password": "123456",
  "name": "Cache Test"
}

### 4) After create, first list call again should be cached: false
GET {{baseUrl}}/users
